version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - /home/portainer/nodered:/data


networks:
  node-red-net: