version: '3.1'
services:
  web:
    image: odoo:15.0
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - odoo-web-config:/etc/odoo
      - odoo-web-addons:/mnt/extra-addons
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    
volumes:
  odoo-web-data:
  odoo-web-config:
  odoo-web-addons:
  odoo-db-data: