version: "3"
services:
  #############
  # mariadb | Mysql Server
  #############
  mariadb:
    image: mariadb:10.9.4
    restart: unless-stopped
    environment:
      - MYSQL_USER=maria
      - MYSQL_ROOT_PASSWORD=w)v!IBFrBrQt6vwZ
      - MYSQL_PASSWORD=w)v!IBFrBrQt6vwZ
    ports:
      - 3306:3306
    volumes:
      - /home/database/datas/mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=w)v!IBFrBrQt6vwZ

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  #############
  # postgres
  #############
  postgres:
    image: postgres:12.13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=w)v!IBFrBrQt6vwZ
    ports:
      - 5432:5432
    volumes:
      - /home/database/datas/postgres:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@homelab.com
      PGADMIN_DEFAULT_PASSWORD: w)v!IBFrBrQt6vwZ
    ports:
      - "8082:80"
    volumes:
      - /home/database/datas/pgadmin:/var/lib/pgadmin

  #############
  # mongo
  #############
  mongo:
    image: mongo:4.4.18
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - /home/database/datas/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: w)v!IBFrBrQt6vwZ

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: w)v!IBFrBrQt6vwZ
      ME_CONFIG_MONGODB_URL: mongodb://mongo:w)v!IBFrBrQt6vwZ@mongo:27017/

  #############
  # influxdb2
  #############
  influxdb2:
    image: influxdb:2.6.1
    container_name: influxdb2
    restart: unless-stopped
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=influx
      - INFLUXDB_ADMIN_PASSWORD=w)v!IBFrBrQt6vwZ
    volumes:
      - /home/database/datas/influxdb2:/var/lib/influxdb2:rw
    ports:
      - 8086:8086

  chronograf:
    image: chronograf:latest
    restart: unless-stopped
    ports:
      - "8888:8888"
    depends_on:
      - influxdb2
    environment:
      - INFLUXDB_URL=http://influxdb2:8086
      - INFLUXDB_USERNAME=influx
      - INFLUXDB_PASSWORD=w)v!IBFrBrQt6vwZ

  #############
  # redis
  #############
  redis:
    image: redis:7.0.8
    command: redis-server --appendonly yes
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - /home/database/datas/redis:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8088:8081
    links:
      - redis:redis
    depends_on:
      - redis
