service:
  type: LoadBalancer

persistence:
  enabled: true
  storageClass: longhorn

mode: distributed ## other supported values are "standalone"

rootUser: "admin"
rootPassword: "------"

# Number of MinIO containers running
replicas: 16
# Number of expanded MinIO clusters
pools: 1
