version: '3'

services:
  tooljet:
    tty: true
    stdin_open: true
    image: tooljet/tooljet-ce:latest
    restart: always
    env_file: stack.env
    ports:
      - 8034:80
    environment:
      SERVE_CLIENT: "true"
      PORT: "80"
    command: npm run start:prod
