version: "3.9"
services:
  nifi:
    image: apache/nifi:1.23.2
    restart: unless-stopped
    environment:
      # NIFI_WEB_HTTP_PORT: 8080
      NIFI_WEB_HTTPS_PORT: 8443
      NIFI_WEB_PROXY_HOST: "192.168.44.198:8443,flow.dev.homelab.xyz,flow.dev.homelab.xyz:443"
      NIFI_WEB_HTTP_HOST: 0.0.0.0
      SINGLE_USER_CREDENTIALS_USERNAME: "admin"
      SINGLE_USER_CREDENTIALS_PASSWORD: "------"
      INITIAL_ADMIN_IDENTITY: admin
    ports:
      # - 8080:8080
      - 8443:8443
    volumes:
      - ./data:/data
      - ./driver:/driver
      - ./extensions:/opt/nifi/nifi-current/extensions

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: hyman
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
